### ISSUE TITLE
passengers should be stacked in floor

### ISSUE THREAD

**Issue by Yousefjb** [idaifallah/elevatorGame#2]
if a new passenger arrive then the old one is removed.
a new img element should be added when a new passenger arrives.

**Comment by idaifallah** [comment]
Why??!
let it be as challenge
if you didn't take him quickly he will go and you will lose his score.

**Comment by Yousefjb** [comment]
actually this will make it less challengeable, there was a passenger you didn't care about and now comes a new one that also you don't care about, it's the same.
On the other side, if you stack passengers this will stress the player and will try to not fulfill the floor with not served passengers.
