### ISSUE TITLE
use offline dependencies

### ISSUE THREAD

**Issue by Yousefjb** [idaifallah/elevatorGame#4]
bootstrap, jQuery and any other dependencies.

**Comment by idaifallah** [comment]
تتدخلش :p
يعني هاي الشغله الوحيده الي عرفتها بالكود :v:

**Comment by idaifallah** [comment]
online is better due to caching

**Comment by Yousefjb** [comment]
how is that better !!!
caching means it becomes local, why not making it local from the start !!
also internet connection is not granted, especially in the ANNU.
